// <auto-generated />
using System;
using GestionEntrenamientoDeportivo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionEntrenamientoDeportivo.Migrations
{
    [DbContext(typeof(DBgestion))]
    partial class DBgestionModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionEntrenamientoDeportivo.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("GestionEntrenamientoDeportivo.Models.CategoriaEjercicio", b =>
                {
                    b.Property<int>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("EjercicioId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("EjercicioCategorias");
                });

            modelBuilder.Entity("GestionEntrenamientoDeportivo.Models.Ejercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RutinaId")
                        .HasColumnType("int");

                    b.Property<string>("SecureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoPublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoSecureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RutinaId");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("GestionEntrenamientoDeportivo.Models.RegistroProgreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<float?>("Peso")
                        .HasColumnType("real");

                    b.Property<int?>("Repeticiones")
                        .HasColumnType("int");

                    b.Property<int?>("Series")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistrosProgreso");
                });

            modelBuilder.Entity("GestionEntrenamientoDeportivo.Models.Rutina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("GestionEntrenamientoDeportivo.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GestionEntrenamientoDeportivo.Models.CategoriaEjercicio", b =>
                {
                    b.HasOne("GestionEntrenamientoDeportivo.Models.Categoria", "Categoria")
                        .WithMany("EjercicioCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEntrenamientoDeportivo.Models.Ejercicio", "Ejercicio")
                        .WithMany("EjercicioCategorias")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Ejercicio");
                });

            modelBuilder.Entity("GestionEntrenamientoDeportivo.Models.Ejercicio", b =>
                {
                    b.HasOne("GestionEntrenamientoDeportivo.Models.Rutina", null)
                        .WithMany("Ejercicios")
                        .HasForeignKey("RutinaId");
                });

            modelBuilder.Entity("GestionEntrenamientoDeportivo.Models.RegistroProgreso", b =>
                {
                    b.HasOne("GestionEntrenamientoDeportivo.Models.Ejercicio", "Ejercicio")
                        .WithMany("RegistrosProgreso")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEntrenamientoDeportivo.Models.Usuario", "Usuario")
                        .WithMany("RegistrosProgreso")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionEntrenamientoDeportivo.Models.Rutina", b =>
                {
                    b.HasOne("GestionEntrenamientoDeportivo.Models.Usuario", "Usuario")
                        .WithMany("Rutinas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionEntrenamientoDeportivo.Models.Categoria", b =>
                {
                    b.Navigation("EjercicioCategorias");
                });

            modelBuilder.Entity("GestionEntrenamientoDeportivo.Models.Ejercicio", b =>
                {
                    b.Navigation("EjercicioCategorias");

                    b.Navigation("RegistrosProgreso");
                });

            modelBuilder.Entity("GestionEntrenamientoDeportivo.Models.Rutina", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("GestionEntrenamientoDeportivo.Models.Usuario", b =>
                {
                    b.Navigation("RegistrosProgreso");

                    b.Navigation("Rutinas");
                });
#pragma warning restore 612, 618
        }
    }
}
